### ISSUE TITLE
Single selects don't work correctly

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#226]
Hey @jackiboy, found another quirk in the `<select>`.

If you have this, in the contenttype:

```
        selectfield:
            type: select
            values:
                foo: Foooo
                bar: Bario
                baz: BAzzazza
```

and create a new record, you can't make a selection: 

<img width="642" alt="screenshot 2019-01-01 at 15 12 51" src="https://user-images.githubusercontent.com/1833361/50573604-bc500000-0dd7-11e9-83eb-524f1e152a56.png">
