### ISSUE TITLE
Default 'escaping' of field output in Twig.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/four#351]
In Bolt 3, if you do `{{ record.fieldname }}`, it'll output HTML. At the same time, it's not *explicitly defined* how it should behave. One of the causes of this is how the fields are stored internally. 

We should make sure that Bolt 4 does this sensibly, consistent and robust. In my opinion, it should work like the following. Let's say we have a title field, with a `<i>` tag in it.

![schermafbeelding 2019-03-07 om 13 59 32](https://user-images.githubusercontent.com/1833361/53958406-4458cb80-40e1-11e9-9c73-87f0dc955248.png)

In Twig we should be able to do: 

```twig
<hr>
    <p>{{ record.title }}</p>
    <p>{{ record.title|raw }}</p>
    <p>{{ record.title|e('html') }}</p>
    <p>{{ dump(record.title) }}</p>
    <p>{{ dump(record.title.getValue()) }}</p>
<hr>
```

And it should output: 

![schermafbeelding 2019-03-07 om 14 07 37](https://user-images.githubusercontent.com/1833361/53958875-66068280-40e2-11e9-9565-c9b91e9a8a40.png)

This way, the _implementor_ can use `{{ record.foo }}` and get the HTML output they expect 90% of the time, and at the same time, you still have access to the underlying data structure to do with it what you need.

**Comment by stryxx** [comment]
@bobdenotter What does happen there when you add to field <script src="../link/to/bitcoin.miner.js"></script>? :)

**Comment by JarJak** [comment]
IMO, since Bolt is a WYSIWYG editor, if an admin puts `<i>Something</i>` in a text or textarea field, he should see `<i>Something</i>` on website. That's because this type of field was not made to store html data but raw text.
On the other hand, if the field has type of html, as admin expects html output on website, so he should see *Something*.

BUT we could add an option to make simple text field behave as html one (e.g. a field to paste some js stuff). Example:
```
ga_script:
    type: text
    safe: true # default: false
```

**Comment by bobdenotter** [comment]
@stryxx Bolt 3 had a whitelist-based filtering for HTML-like fields, where input would be sanitized before going into the database. In Bolt 3's config.yml, you had: 

```yaml
# Define the HTML tags and attributes that are allowed in 'cleaned' HTML. This
# is used for sanitizing HTML, to make sure there are no undesirable elements
# left in the content that is shown to users. For example, tags like `<script>`
# or `onclick`-attributes.
# Note: enabling options in the `wysiwyg` settings will implicitly add items to
# the allowed tags. For example, if you set `images: true`, the `<img>` tag
# will be allowed, regardless of it being in the `allowed_tags` setting.
htmlcleaner:
    allowed_tags: [ div, span, p, br, hr, s, u, strong, em, i, b, li, ul, ol, mark, blockquote, pre, code, tt, h1, h2, h3, h4, h5, h6, dd, dl, dt, table, tbody, thead, tfoot, th, td, tr, a, img, address, abbr, iframe, caption, sub, sup, figure, figcaption ]
    allowed_attributes: [ id, class, style, name, value, href, src, alt, title, width, height, frameborder, allowfullscreen, scrolling, target, colspan, rowspan ]
```

This meant that `<script>` would be filtered out, but `<i>` didn't.
